import type { MetadataRoute } from "next";
import { siteConfig } from "@/lib/site";

/**
 * robots.txt groups do not inherit from one another — a crawler obeys only the
 * single most specific User-Agent block that matches it (RFC 9309) — so every
 * named bot has to repeat these rules or it inherits no restrictions at all.
 */
const allow = [
  "/",
  // Every page's og:image is generated by this route, so crawlers that honour
  // robots.txt need it reachable or link previews render blank.
  "/api/og",
];

// "/admin$" pins the bare route, so a CMS page such as /admin-training — which
// a bare "/admin" prefix would also match — stays crawlable.
const disallow = ["/admin$", "/admin/", "/api/"];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: "*", allow, disallow },
      { userAgent: "GPTBot", allow, disallow },
    ],
    sitemap: `${siteConfig.url}/sitemap.xml`,
    // The Host directive takes a bare hostname, never a full URL.
    host: siteConfig.url.replace(/^https?:\/\//, ""),
  };
}
